[server]
headless = true
port = 8501
enableCORS = false

[theme]
base = "light"
primaryColor = "#004080"
backgroundColor = "#f0f2f6"
secondaryBackgroundColor = "#ffffff"
textColor = "#000000"
font = "sans serif"

[browser]
gatherUsageStats = false
